# Generated by Django 2.2.6 on 2020-02-03 11:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200128_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite uma linguagem para o livro: (e.g. English, French, Japanese etc.)', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID exclusivo para este livro em particular em toda a biblioteca', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Manutenção'), ('p', 'Por empréstimo'), ('a', 'Acessível'), ('r', 'Reservado')], default='a', help_text='Livro disponível', max_length=1),
        ),
        migrations.CreateModel(
            name='AuthorBookIntance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID exclusivo para este Autor em particular em toda a biblioteca', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('L', 'Locado'), ('D', 'Disponível')], default='D', help_text='Disponivel', max_length=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
            ],
            options={
                'ordering': ['due_back'],
                'permissions': (('can_mark_returned', 'Definir Autor.'),),
            },
        ),
    ]
