# Generated by Django 2.2.6 on 2020-02-04 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_auto_20200203_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['book', 'author'],
            },
        ),
        migrations.AlterField(
            model_name='genero',
            name='name',
            field=models.CharField(help_text='Entre com o genero (e.g. Ficcao ciêntifica, infantil, terror, drama)', max_length=200),
        ),
        migrations.CreateModel(
            name='EmprestaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID exclusivo em particular em toda a biblioteca', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Manutenção'), ('p', 'Por empréstimo'), ('a', 'Acessível'), ('r', 'Reservado')], default='a', help_text='Acessíve', max_length=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
                ('empresta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Empresta')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
